### PR TITLE
Pinning GeoTrust root CA instead of unique server certs.

### PR DESCRIPTION
**Pull request by merickson**
Removed server-specific pins, added GeoTrust CA certs to the client. This will enable us to keep updating the `spideroak.com` certificate without having to carefully coordinate certificate updates.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/SpiderOak/SpiderOakMobileClient/pull/730%23issuecomment-165874451%22%2C%20%22https%3A//github.com/SpiderOak/SpiderOakMobileClient/pull/730%23issuecomment-165876942%22%2C%20%22https%3A//github.com/SpiderOak/SpiderOakMobileClient/pull/730%23issuecomment-165877626%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/SpiderOak/SpiderOakMobileClient/pull/730%23issuecomment-165874451%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40merickson%2C%20do%20the%20certs%20all%20just%20get%20pulled%20in%20by%20the%20build%2C%20or%20does%20some%20code%20have%20to%20change%20to%20get%20the%20new%20ones%3F%20Ie%2C%20is%20this%20change%20self-contained%2C%20or%20is%20there%20more%20pending%3F%22%2C%20%22created_at%22%3A%20%222015-12-18T19%3A15%3A16Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/515685%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/kenmanheimer%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40kenmanheimer%20%2C%20completely%20self-contained%20as%20long%20as%20there%27s%20no%20dangling%20build%20artifacts-%20I%20think%20you%20added%20%60grunt%20debug%3A%21%60%20for%20this%20sorta%20thing.%20The%20code%20in%20both%20Cordova-HTTP%20and%20File%20Download%20Plugin%20slurp%20up%20all%20the%20certs%20and%20will%20return%20OK%20if%20one%20of%20these%20certs%20appears%20anywhere%20in%20the%20certificate%20chain%20presented%20by%20the%20server.%22%2C%20%22created_at%22%3A%20%222015-12-18T19%3A27%3A45Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/734363%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/merickson%22%7D%7D%2C%20%7B%22body%22%3A%20%22Too%20good%21%20%28-%25%22%2C%20%22created_at%22%3A%20%222015-12-18T19%3A30%3A45Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/515685%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/kenmanheimer%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/SpiderOak/SpiderOakMobileClient/pull/730#issuecomment-165874451'>General Comment</a></b>
- <a href='https://github.com/kenmanheimer'></a> @merickson, do the certs all just get pulled in by the build, or does some code have to change to get the new ones? Ie, is this change self-contained, or is there more pending?
- <a href='https://github.com/merickson'></a> @kenmanheimer , completely self-contained as long as there's no dangling build artifacts- I think you added `grunt debug:!` for this sorta thing. The code in both Cordova-HTTP and File Download Plugin slurp up all the certs and will return OK if one of these certs appears anywhere in the certificate chain presented by the server.
- <a href='https://github.com/kenmanheimer'></a> Too good! (-%

<a href='https://www.codereviewhub.com/SpiderOak/SpiderOakMobileClient/pull/730?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/SpiderOak/SpiderOakMobileClient/pull/730?approve=1'></a>&nbsp;<a href='https://github.com/SpiderOak/SpiderOakMobileClient/pull/730'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by kenmanheimer** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/SpiderOak/SpiderOakMobileClient/pull/730'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by kenmanheimer** [comment]
@merickson, do the certs all just get pulled in by the build, or does some code have to change to get the new ones? Ie, is this change self-contained, or is there more pending?

**Comment by merickson** [comment]
@kenmanheimer , completely self-contained as long as there's no dangling build artifacts- I think you added `grunt debug:!` for this sorta thing. The code in both Cordova-HTTP and File Download Plugin slurp up all the certs and will return OK if one of these certs appears anywhere in the certificate chain presented by the server.

**Comment by kenmanheimer** [comment]
Too good! (-%

**Pull request merged**
